extends Node
## Autoload singleton ("AudioManager"). Plays SFX by name through a pool of
## AudioStreamPlayers on the "SFX" bus. Call AudioManager.play("slash").
##
## Each game event maps to one or more real Kenney .ogg files in
## res://Assets/Audio/; play() picks a random variant so repeats don't sound
## robotic. Unknown names / missing files are ignored so nothing ever crashes.

const AUDIO_DIR := "res://Assets/Audio/"
const POOL_SIZE := 16

# Game event -> list of Kenney files (without the folder). Multiple = random pick.
const SOUNDS := {
	"slash": ["knifeSlice.ogg", "knifeSlice2.ogg"],
	"heavy": ["chop.ogg"],
	"hit": ["impactPunch_medium_000.ogg", "impactPunch_medium_001.ogg", "impactPunch_medium_002.ogg", "impactPunch_medium_003.ogg", "impactPunch_medium_004.ogg"],
	"enemy_hurt": ["impactSoft_medium_000.ogg", "impactSoft_medium_001.ogg", "impactSoft_medium_002.ogg", "impactSoft_medium_003.ogg", "impactSoft_medium_004.ogg"],
	"player_hurt": ["impactPlate_medium_000.ogg", "impactPlate_medium_001.ogg", "impactPlate_medium_002.ogg", "impactPlate_medium_003.ogg", "impactPlate_medium_004.ogg"],
	"enemy_death": ["impactPunch_heavy_000.ogg", "impactPunch_heavy_001.ogg", "impactPunch_heavy_002.ogg", "impactPunch_heavy_003.ogg", "impactPunch_heavy_004.ogg"],
	"dash": ["cloth1.ogg", "cloth2.ogg", "cloth3.ogg", "cloth4.ogg"],
	"projectile": ["drawKnife1.ogg", "drawKnife2.ogg", "drawKnife3.ogg"],
	"charge": ["creak1.ogg", "creak2.ogg", "creak3.ogg"],
	"telegraph": ["metalClick.ogg"],
	"pickup": ["handleCoins.ogg", "handleCoins2.ogg"],
	"upgrade": ["metalLatch.ogg"],
	"room_clear": ["impactBell_heavy_000.ogg", "impactBell_heavy_001.ogg"],
	"game_over": ["game_over.ogg"],
	"door_close": ["doorClose_1.ogg", "doorClose_2.ogg", "doorClose_3.ogg", "doorClose_4.ogg"],
	"door_open": ["doorOpen_1.ogg", "doorOpen_2.ogg"],
	"click": ["click1.ogg", "click2.ogg", "click3.ogg"],
}

# Per-event random pitch spread so repeats vary. Defaults to a small amount.
const VARIATION := {
	"slash": 0.1, "hit": 0.12, "enemy_hurt": 0.12, "heavy": 0.08,
	"enemy_death": 0.1, "projectile": 0.1, "dash": 0.08,
}

# Looping ambient beds (generated by tools/generate_music.py).
const MUSIC := {
	"calm": "music_calm.wav",
	"combat": "music_combat.wav",
}
const MUSIC_DB := -11.0

# The mix as authored in default_bus_layout.tres. The player's 0..1 volume
# sliders scale *from* these, so "100%" means "the level the game was mixed at",
# not "0 dB". Keeps SFX and music balanced against each other at every setting.
const BUS_BASE_DB := {"master": 0.0, "sfx": -4.0, "music": -12.0}
const BUS_NAMES := {"master": "Master", "sfx": "SFX", "music": "Music"}

var _streams: Dictionary = {}   # name -> Array[AudioStream]
var _players: Array[AudioStreamPlayer] = []
var _next: int = 0
var _duck_token: int = 0

var _music_player: AudioStreamPlayer
var _music_streams: Dictionary = {}
var _current_music: String = ""


func _ready() -> void:
	for i in POOL_SIZE:
		var p := AudioStreamPlayer.new()
		p.bus = "SFX"
		# Menus pause the tree, so without this the click on "Resume" (and every
		# other paused-UI sound) is silently swallowed.
		p.process_mode = Node.PROCESS_MODE_ALWAYS
		add_child(p)
		_players.append(p)
	_load_all()
	_music_player = AudioStreamPlayer.new()
	_music_player.bus = "Music"
	_music_player.process_mode = Node.PROCESS_MODE_ALWAYS  # keep playing while paused
	add_child(_music_player)
	_load_music()
	# Note: the saved volumes are pushed by MetaProgression._ready(), which runs
	# *after* this autoload. Applying here would only ever apply the defaults.


# --- Volume ------------------------------------------------------------------
## Push the saved 0..1 slider values onto the audio buses. Called at startup and
## whenever the options panel changes a slider.
func apply_volume_settings() -> void:
	for key in BUS_NAMES:
		var bus := AudioServer.get_bus_index(BUS_NAMES[key])
		if bus < 0:
			continue
		AudioServer.set_bus_mute(bus, _slider(key) <= 0.001)
		AudioServer.set_bus_volume_db(bus, _bus_base_db(key))


## The dB this bus should currently sit at: the authored mix level, offset by
## the player's slider.
func _bus_base_db(key: String) -> float:
	var linear := _slider(key)
	if linear <= 0.001:
		return -80.0
	return float(BUS_BASE_DB.get(key, 0.0)) + linear_to_db(linear)


## Slider value, tolerating being called before the MetaProgression autoload
## exists (this autoload is registered first).
func _slider(key: String) -> float:
	var meta := get_node_or_null(^"/root/MetaProgression")
	if meta == null:
		return 1.0
	return clampf(meta.get_volume(key), 0.0, 1.0)


func _load_all() -> void:
	for event in SOUNDS:
		var variants: Array = []
		for file in SOUNDS[event]:
			var path: String = AUDIO_DIR + file
			if ResourceLoader.exists(path):
				var stream := load(path)
				if stream:
					variants.append(stream)
		if not variants.is_empty():
			_streams[event] = variants


## Play a named event. `pitch` overrides the random pitch when > 0.
func play(sound: String, volume_db: float = 0.0, pitch: float = 0.0) -> void:
	var variants = _streams.get(sound)
	if variants == null or variants.is_empty():
		return
	var p := _players[_next]
	_next = (_next + 1) % _players.size()
	p.stream = variants[randi() % variants.size()]
	p.volume_db = volume_db
	if pitch > 0.0:
		p.pitch_scale = pitch
	else:
		var spread: float = VARIATION.get(sound, 0.06)
		p.pitch_scale = 1.0 + randf_range(-spread, spread)
	p.play()


func _load_music() -> void:
	for key in MUSIC:
		var path: String = AUDIO_DIR + MUSIC[key]
		if not ResourceLoader.exists(path):
			continue
		var s = load(path)
		if s is AudioStreamWAV:
			s.loop_mode = AudioStreamWAV.LOOP_FORWARD
			s.loop_begin = 0
			s.loop_end = int(s.get_length() * s.mix_rate)
		if s:
			_music_streams[key] = s


## Crossfade to a looping music bed by key ("calm" / "combat"). No-op if that
## track is already playing, so it survives scene changes seamlessly.
func play_music(track: String, volume_db: float = MUSIC_DB, fade: float = 1.2) -> void:
	if _music_player == null:
		return
	if track == _current_music and _music_player.playing:
		return
	_current_music = track
	var stream = _music_streams.get(track)
	if stream == null:
		return
	var tw := create_tween()
	tw.set_ignore_time_scale(true)
	if _music_player.playing:
		tw.tween_property(_music_player, "volume_db", -40.0, fade * 0.4)
	tw.tween_callback(func() -> void:
		_music_player.stream = stream
		_music_player.volume_db = -40.0
		_music_player.play())
	tw.tween_property(_music_player, "volume_db", volume_db, fade)


func stop_music(fade: float = 0.8) -> void:
	_current_music = ""
	if _music_player == null or not _music_player.playing:
		return
	var tw := create_tween()
	tw.set_ignore_time_scale(true)
	tw.tween_property(_music_player, "volume_db", -40.0, fade)
	tw.tween_callback(_music_player.stop)


## A low-pitched layer under a heavy impact — a fake sub-bass "thump".
func thump(volume_db: float = -3.0) -> void:
	play("heavy", volume_db, 0.45)


## Briefly lower the Music bus BY `db` (a negative offset), then ease it back
## over `duration`. Used during slow-mo. No-ops if there's no Music bus.
##
## The duck is relative to the player's configured music level and restores to
## that same level. It used to set an absolute db and restore to 0.0, which
## meant every slow-mo permanently *raised* the music bus to full volume — the
## music got louder and louder the longer you played.
func duck_music(db: float, duration: float) -> void:
	var bus := AudioServer.get_bus_index("Music")
	if bus < 0:
		return
	_duck_token += 1
	var my := _duck_token
	AudioServer.set_bus_volume_db(bus, _bus_base_db("music") + db)
	var t := get_tree().create_timer(maxf(0.05, duration), true, false, true)
	await t.timeout
	if my == _duck_token:
		AudioServer.set_bus_volume_db(bus, _bus_base_db("music"))
